// Generated by Wrangler on Mon Aug 05 2024 20:07:01 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	TestDurable: DurableObjectNamespace<import("./src/index").TestDurable>;
}
