// Generated by Wrangler on Sun Aug 11 2024 18:08:50 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	GROQ_API_KEY: "";
	TestDurable: DurableObjectNamespace<import("./src/index").TestDurable>;
}
