// Generated by Wrangler on Tue Aug 13 2024 11:45:23 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

// interface Env {
// 	GROQ_API_KEY: "";
// 	TestDurable: DurableObjectNamespace<import("./src/index").TestDurable>;
// 	MY_RATE_LIMITER: any;
// }
